################################################################################################
#                                                                                              #
#                                  SwornRPG Configuration File                                 #
#                                      Created by dmulloy2                                     #
#  Detailed explanation here: http://dev.bukkit.org/server-mods/swornrpg/pages/configuration/  #
#                                                                                              #
################################################################################################

updatechecker: true
#Enables/disables checking for updates

irondoorprotect: true
#Enables/disables the protection of iron doors

randomdrops: true
#Enables/disables the random chance that a random drop will drop from a block

axekb: true
#Enables/disables the random chance that players can get knocked back by axes

arrowfire: true
#Enables/disables the random chance that players can catch fire when shot by arrows

deathbook: true
#Will a player receive a book/message with their death coordinates?
#If essentials is found, the plugin will send a mail message. If not, it will give a book

frenzy:
  enabled: true
  #Is frenzy enabled?
  baseduration: 7.5
  #Make this integer low.(Formula = baseduration x level)
  #Example: a player that is level 2 with a base duration of 30 would get frenzy for a minute
  
levelingmethods:
#How can players level up?
  onlinetime:
    enabled: true
  mcxpgain:
    enabled: true
    xpgain: 15
    #how much xp a player gains when they level up using MC xp
  playerkills:
    enabled: true
    xpgain: 25
    #xp gained when a player kills
    xploss: 10
    #xp lost when a player dies
  mobkills:
    enabled: true
    xpgain: 5
    #xp gain when a player kills a mob
  
levelingrewards:
#What do players receieve for leveling up?
  money:
    enabled: true
    amountperlevel: 250
  #minecraft-xp: false
  items:
    enabled: true
    itemid: 264
    #Item id of the item you wish to reward (Defaults to diamond)
    amountperlevel: 2

