#SwornRPG Config File
#Created by dmulloy2
debug: false
frenzy:
  on: true
  duration: 10
    #Time (in seconds) how long the default frenzy mode will last
level-up-rewards:
  on: true
level-up-methods:
  mob-xp: true
  online-time: false
  player-kills: true
  ore-mining: false
  #More to come soon
max-levels: 25
bonus-up:
  on: true
  ##Bonus plugin XP
double-up:
  on: true
  ##Bonus MC XP

