#SwornRPG Config File
#Created by dmulloy2
#Detailed explanation here: http://dev.bukkit.org/server-mods/swornrpg/pages/configuration/

irondoorprotect: true
#Enables/disables the protection of iron doors
randomdrops: true
#Enables/disables the random chance that a random drop will drop from a block
axekb: true
#Enables/disables the random chance that players can get knocked back by axes
arrowfire: true
#Enables/disables the random chance that players can catch fire when shot by arrows
tagapi: false
#Enables/disables TagAPI integration. Currently worthless.

#Features for future versions:
#frenzy:
 #enabled: true
#levelingmethods:
 #onlinetime: true
 #mining: false
 #playerkills: true
 #mobkills: true
#levelrewards:
 #money: true
 #items: true


