name: SwornRPG
main: net.dmulloy2.swornrpg.SwornRPG
version: 1.2.4
author: dmulloy2
description: The mcMMO Alternative
softdepend: [TagAPI, Essentials, Factions, Vault]
commands:
  a:
    description: Admin only chat
    permission: srpg.adminchat
    usage: /<command> <message>
    aliases: [adminchat]
  ride:
    description: Get on someones head
    permission: srpg.ride
    usage: /<command> <player>
    aliases: [mount]
  unride:
    description: Get off someone's head
    permission: srpg.ride
    usage: /<command>
    aliases: [dismount]
  hat:
    description: Puts the block in your hand on your head
    permission: srpg.hat
    usage: |
      /<command>
      /<command> [remove]
    aliases: [headgear]
  asay:
    description: Alternate admin say command
    permission: srpg.asay
    usage: /<command> <message>
    aliases: [adm]
  srpg:
    description: SwornRPG root command
    usage: |
      /<command>
      /<command> <args>
    aliases: [swornrpg]
  frenzy:
    description: Gives special abilities based on level
    usage: /<command>
  hc:
    description: High Council Chat
    permission: srpg.council
    usage: /<command> <message>
    aliases: [council, highcouncil]
  eject:
    description: Kick someone off your head
    permission: srpg.ride
    usage: /<command>
  match:
    description: Match online and offline players
    permission: srpg.match
    usage: /<command> <player>
    aliases: [matchplayer]
  tag:
    description: Change the tag above your head
    permission: srpg.tag
    usage: /<command> [player] <tag>
    aliases: [playertag, settag, nametag]
  removetag:
    description: Removes/resets a player's tag
    permission: srpg.tagr
    usage: /<command> [player] <tag>
    aliases: [resettag, rtag, tagr, tagreset]
  level:
    description: Shows a player's level
    usage: /<command> [player]
  levelr:
    description: Resets a player's level
    permission: srpg.levelr
    usage: /<command> [player]
    aliases: [resetlevel, levelc, clearlevel]
  deathbook:
    description: Toggles death coordinate books
    usage: /<command>
    aliases: [deathbooktoggle, deathmessage, deathmessagetoggle]
  propose:
    description: Propose to another player
    usage: /<command> <player>
    aliases: [engage]
  marry:
    description: Marry another player
    usage: /<command> <player>
    aliases: [matrimony]
  spouse:
    description: Shows information on a player's spouse
    usage: /<command> [player]
    aliases: [spouseinfo, marryinfo]
  divorce:
    description: Divorce your spouse
    usage: /<command>
    aliases: [unmarry, divorcespouse]
permissions:
  srpg.admin:
    description: Gives access to features meant for server admins
    default: false
    children:
      srpg.moderator: true
      srpg.asay: true
      srpg.aclear: true
      srpg.council: true
      srpg.tag: true
      srpg.tagr: true
      srpg.othertag: true
      srpg.levelr: true
  srpg.*:
    description: Just an alias for srpg.admin
    default: op
    children:
      srpg.admin: true
  srpg.moderator:
    description: Gives access to features meant for server moderators
    default: false
    children:
      srpg.guard: true
      srpg.ride: true
      srpg.match: true
  srpg.guard:
    description: Gives access to features meant for server guards
    default: false
    children:
      srpg.adminchat: true
  srpg.hat:
    default: true
  srpg.ride:
    default: false
  srpg.asay:
    default: false
  srpg.council:
    default: false
  srpg.aclear:
    default: false
  srpg.adminchat:
    default: false
  srpg.tag:
    default: false
  srpg.removetag:
    default: false
  srpg.othertag:
    default: false
  srpg.levelr:
    default: false