name: SwornRPG
main: net.dmulloy2.swornrpg.SwornRPG
version: 0.8.1
author: dmulloy2
description: A better version of McMMO.
softdepend: [TagAPI]
commands: 
  a:
    description: Admin chat.
    usage:
    permission: srpg.adminchat
  ride:
    description: Get on someones head.
    usage:
    aliases: [unride]
    permission: srpg.ride
  hat:
    description: Lets you put the block in you hand on your head.
    usage: 
  dmu:
    description: dmulloy's special chat.
    usage:
  adm:
    description: Alternate admin say command.
    usage:
    permission: srpg.asay
  srpg:
    description: Root command
    usage:
    aliases: [swornrpg]
  frenzy:
    description: Enters beast mode
    usage:
  hc:
    description: High Council Chat
    usage:
    permission: srpg.council
permissions:
  srpg.admin:
    description: Gives access to features meant for server admins.
    children:
      srpg.moderator: true
      srpg.asay: true
      srpg.aclear: true
  srpg.moderator:
    description: Gives access to features meant for server moderators.
    children:
      srpg.guard: true
      srpg.ride: true
  srpg.guard:
    description: Gives access to features meant for server guards.
    children:
      srpg.adminchat: true
