name: SwornRPG
main: net.dmulloy2.swornrpg.SwornRPG
version: 0.9.1
author: dmulloy2
description: The MCMMO Alternative
softdepend: [TagAPI]
commands: 
  a:
    description: Admin chat.
    permission: srpg.adminchat
    usage: /<command> <message>
  ride:
    description: Get on someones head.
    permission: srpg.ride
    usage: /<command> <player>
  unride:
    description: Get off someone's head.
    permission: srpg.ride
    usage: /<command>
  hat:
    description: Puts the block in your hand on your head.
    permission: srpg.hat
    usage: |
      /<command> 
      /<command> <remove>
  asay:
    description: Alternate admin say command.
    permission: srpg.asay
    usage: /<command> <message>
  srpg:
    description: SwornRPG root command.
    usage: |
      /<command>
      /<command> <args>
  frenzy:
    description: Gives special abilities based on level.
    usage: /<command>
  hc:
    description: High Council Chat.
    permission: srpg.council
    usage: /<command> <message>
permissions:
  srpg.admin:
    description: Gives access to features meant for server admins.
    children:
      srpg.moderator: true
      srpg.asay: true
      srpg.aclear: true
      srpg.council: true
      srpg.guard: true
  srpg.moderator:
    description: Gives access to features meant for server moderators.
    children:
      srpg.guard: true
      srpg.ride: true
  srpg.guard:
    description: Gives access to features meant for server guards.
    children:
      srpg.adminchat: true