name: SwornRPG
main: net.dmulloy2.swornrpg.SwornRPG
version: 0.8.3
author: dmulloy2
description: A better version of McMMO.
softdepend: [TagAPI]
commands: 
  a:
    description: Admin chat.
    usage: |
      /<command> <message>
    permission: srpg.adminchat
  ride:
    description: Get on someones head.
    usage: |
      /<command> <player>
    permission: srpg.ride
  unride:
    description: Gets off someone's head.
    usage: |
      /<command>
    permission: srpg.ride
  hat:
    description: Lets you put the block in you hand on your head.
    usage: |
      /<command> <remove>
  dmu:
    description: dmulloy's special chat.
    usage: |
      /<command> <message>
  adm:
    description: Alternate admin say command.
    usage: |
      /<command> <message>
    permission: srpg.asay
  srpg:
    description: Root command
    usage: |
      /<command> <args>
    aliases: [swornrpg]
  frenzy:
    description: Enters beast mode
    usage: |
      /<command>
  hc:
    description: High Council Chat
    usage: |
      /<command> <message>
    permission: srpg.council
permissions:
  srpg.admin:
    description: Gives access to features meant for server admins.
    children:
      srpg.moderator: true
      srpg.asay: true
      srpg.aclear: true
  srpg.moderator:
    description: Gives access to features meant for server moderators.
    children:
      srpg.guard: true
      srpg.ride: true
  srpg.guard:
    description: Gives access to features meant for server guards.
    children:
      srpg.adminchat: true
