name: SwornRPG
main: net.dmulloy2.swornrpg.SwornRPG
version: 0.9.3
author: dmulloy2
description: The MCMMO Alternative
commands: 
  a:
    description: Admin chat.
    permission: srpg.adminchat
    usage: /<command> <message>   
  ride:
    description: Get on someones head.
    permission: srpg.ride
    usage: /<command> <player> 
  unride:
    description: Get off someone's head.
    permission: srpg.ride
    usage: /<command>
  hat:
    description: Puts the block in your hand on your head.
    permission: srpg.hat
    usage: |
      /<command> 
      /<command> <remove>
  asay:
    description: Alternate admin say command.
    permission: srpg.asay
    usage: /<command> <message>
  srpg:
    description: SwornRPG root command.
    usage: |
      /<command>
      /<command> <args>
  frenzy:
    description: Gives special abilities based on level.
    usage: /<command>
  hc:
    description: High Council Chat.
    permission: srpg.council
    usage: /<command> <message>
  eject:
    description: Kick someone off your head.
    permission: srpg.ride
    usage: /<command>
permissions:
  srpg.admin:
    description: Gives access to features meant for server admins.
    default: false
    children:
      srpg.moderator: true
      srpg.asay: true
      srpg.aclear: true
      srpg.council: true
  srpg.*:
    description: Just an alias for srpg.admin
    default: op
    children:
      srpg.admin: true
  srpg.moderator:
    description: Gives access to features meant for server moderators.
    default: false
    children:
      srpg.guard: true
      srpg.ride: true
  srpg.guard:
    description: Gives access to features meant for server guards.
    default: false
    children:
      srpg.adminchat: true
  srpg.hat:
    default: true
  srpg.ride:
    default: false
  srpg.asay:
    default: false
  srpg.council:
    default: false
  srpg.aclear:
    default: false
  srpg.adminchat:
    default: false