#######################################################################################
#+-----------------------------------------------------------------------------------+#
#|                                                                                   |#
#|                                SwornRPG Configuration                             |#
#|                                     By: dmulloy2                                  |#
#|                                                                                   |#
 #+----------------------------------------------------------------------------------+#
 ######################################################################################

# This is the main configuration file for SwornRPG
# It follows standard YAML procedure
# If there is an error on startup, make sure the config matches up with this:
# https://github.com/dmulloy2/SwornRPG/blob/master/src/main/resources/config.yml
# Input: boolean - true/false, String - "text", integer - number

#############################################
#+-----------------------------------------+#
#|          Global Configuration           |#
#+-----------------------------------------+#
#############################################

# Extra output to console (boolean)
debug: false

# Marriage (boolean)
marriage: true

# MobSpawner Camping Radius (integer)
campingRadius: 32

# Worlds SwornRPG is disabled in (world)
disabledWorlds:
- disabled_world

#############################################
#+-----------------------------------------+#
#|                 Salvaging               |#
#+-----------------------------------------+#
#############################################

# Salvaging Enabled (boolean)
salvaging: true

# Items that can be salvaged, formatted: "id, Material, how many items it returns; ...; lastid, Lastmaterial, lastitems"
salvage: "306, Iron, 5; 307, Iron, 8; 308, Iron, 7; 309, Iron, 4; 310, Diamond, 5; 311, Diamond, 8; 312, Diamond, 7; 313, Diamond, 4; 314, Gold, 5; 315, Gold, 8; 316, Gold, 7; 317, Gold, 4; 267, Iron, 2; 256, Iron, 1; 257, Iron, 3; 258, Iron, 3; 292, Iron, 2; 276, Diamond, 2; 277, Diamond, 1; 278, Diamond, 3; 279, Diamond, 3; 293, Diamond, 2; 283, Gold, 2; 284, Gold, 1; 285, Gold, 3; 286, Gold, 3; 294, Gold, 2"

#############################################
#+-----------------------------------------+#
#|              AutoSave Task              |#
#+-----------------------------------------+#
#############################################

# Interval in minutes (integer)
# Safe to use - no longer lags the server
autoSave:
  enabled: false
  interval: 120

#############################################
#+-----------------------------------------+#
#|                Abilities                |#
#+-----------------------------------------+#
#############################################
  
# Duration (in seconds) = baseduration + (levelmultiplier x level)
# Cooldown (in seconds) = duration x cooldownmultiplier
# Inputs: enabled - boolean, rest - integer

# Frenzy Mode
frenzy:
  enabled: true
  baseDuration: 5
  levelMultiplier: 1
  cooldownMultiplier: 10

# SuperPickaxe
superPickaxe:
  enabled: true
  baseDuration: 10
  levelMultiplier: 2
  cooldownMultiplier: 2

# Unlimited Ammo
unlimitedAmmo:
  enabled: true
  baseDuration: 10
  levelMultiplier: 2
  cooldownMultiplier: 2

#############################################
#+-----------------------------------------+#
#|                Leveling                 |#
#+-----------------------------------------+#
#############################################

# How much xp a player gains when doing a particular task
# Inputs: enabled - boolean, xpgain/loss - integer

levelingMethods:
  # Minecraft XP Gain
  mcXpGain:
    enabled: true
    xpgain: 15
  # PVP
  playerKills:
    enabled: true
    xpgain: 25
    xploss: 10
  # PVE
  mobKills:
    enabled: true
    xpgain: 5
  # Minute of online time
  onlineTime:
    enabled: true
    xpgain: 1
  # Taming
  taming:
    enabled: true
    xpgain: 5
  # Fishing
  fishing:
    enabled: true
    xpgain: 5
  # Farming
  herbalism:
    enabled: true
    xpgain: 1
  # Enchanting
  enchanting:
    enabled: true
    xpgain: 5

#############################################
#+-----------------------------------------+#
#|                Rewards                  |#
#+-----------------------------------------+#
#############################################

# Levelup Rewards
# Enabled - boolean
# Money - integer
# Items - List<Item>

levelingRewards:
  enabled: true
  money: 250
  items:
    - "diamond, 1"
 
#############################################
#+-----------------------------------------+#
#|              Health Bars                |#
#+-----------------------------------------+#
#############################################

# Player and Mob health bars
# Inputs: enabled - boolean

mobHealthBars:
  enabled: true

playerHealthBars:
  enabled: false

#############################################
#+-----------------------------------------+#
#|            Miscellaneous                |#
#+-----------------------------------------+#
#############################################

# Confusion - when a player punches another player in the face
# Enabled - boolean.
# Duration (integer) in seconds.
# Strength (integer) - potion strength

confusion:
  enabled: true
  duration: 3
  strength: 1
  
# Speed Boost - random chance of a player speeding up
# Enabled - boolean.
# Odds (integer) chance (1 out of odds)
# Duration (integer) in seconds.
# Strength (integer) speed boost strength

speedBoost:
  enabled: true
  odds: 20
  duration: 2
  strength: 1
  
# Graceful Roll - random chance of a player not taking fall damage
# Enabled - boolean.
# Odds (integer) chance (1 out of odds)

gracefulRoll:
  enabled: true
  odds: 50

# Insta-Kill - random chance of a player instantly killing a mob
# Enabled - boolean
# Odds (integer) chance (1 out of odds)

instaKill:
  enabled: true
  odds: 100

# Arrow Fire - random chance of a player catching on fire when hit with arrows
# Enabled - boolean
# Odds (integer) chance (1 out of odds)

arrowFire:
  enabled: true
  odds: 10

# Axe Knockback - random chance of a player getting knocked back by axes
# Enabled - boolean
# Odds (integer) chance (1 out of odds)

axeKnockback:
  enabled: true
  odds: 8

# Iron Door protection (boolean)
ironDoorProtection: true

# Death Coordinate Messages (boolean)
deathCoordinateMessages: true

 
#############################################
#+-----------------------------------------+#
#|               Block Drops               |#
#+-----------------------------------------+#
#############################################
    
# Enabled (boolean)
blockDropsEnabled: true 

# Items Dropped
# Format: 
#  [blockId]:
#    - "rewardId:chance out of 100"
blockDropItems:
  0:
    - "2258:10000"
    - "2259:10000"
    - "2260:10000"
    - "2261:10000"
    - "2262:10000"
    - "2263:10000"
    - "2264:10000"
    - "2265:10000"
    - "2266:10000"  
    - "2267:10000"
    - "46:1000"
    - "49:1000"
    - "264:1000"
    - "384:5000"
    - "388:5000"
    - "399:50000"
    - "266:1000"
    - "265:1000"
    - "406:200"
    - "154:1000"
    - "404:1000"  
  82:
    - "341:20"
    - "287:20"
    - "318:20"
    - "30:100"
  2:
    - "361:30"
    - "392:30"
    - "391:30"
  1:
    - "15:75"
    - "263:25"
    - "21:100"
    - "14:200"
  17:
    - "338:20"
    - "32:200"
    - "127:100"
  4:
    - "389:20"
    - "48:20"
    - "67:50"
    - "145:200"
    - "386:100"
  121:
    - "116:150"
    - "394:25"
    - "388:500"
    - "368:25"
  35:
    - "30:100"
    - "287:15"
  102:
    - "102:2"
  20:
    - "102:10"
    - "20:2"
    - "374:100"
  5:
    - "280:10"
    - "65:20"
    - "85:50"
    - "53:10"
  87:
    - "385:15"
    - "372:25"
    - "112:10"
    - "153:50"
  88:
    - "378:100"
    - "372:25"
    - "331:25"
    - "397:300"
  24:
    - "28:15"
    - "12:15"
    - "390:30"
  12:
    - "338:15"
    - "349:15"
    - "295:30"
  18:
    - "106:15"
    - "111:15"
    - "127:200"
  3:
    - "392:30"
    - "391:30"
    - "357:30"
    - "395:100"
    - "330:100"
  13:
    - "289:15"
    - "352:10"
    - "87:50"
  6:
    - "352:150"
    - "18:25"
    - "32:500"
    - "280:25"
  31:
    - "361:150"
    - "31:5"
    - "362:150"
    - "30:25"
  32:
    - "361:150"
    - "32:5"
    - "362:150"
    - "30:25"
  37:
    - "18:25"
    - "371:150"
    - "39:25"
  38:
    - "18:25"
    - "372:150"
    - "40:25"
  39:
    - "99:10"
    - "372:150"
    - "37:25"
  40:
    - "100:10"
    - "372:150"
    - "38:25"
  59:
    - "293:1000"
    - "295:5"
    - "392:150"
    - "297:25"
  59:
    - "293:1000"
    - "295:5"
    - "392:150"
    - "297:25"
  81:
    - "382:500"
    - "262:15"
    - "267:1000"
    - "373:25"
  83:
    - "368:1000"
    - "353:15"
    - "362:150"
    - "18:25"
  86:
    - "400:200"
    - "91:15"
    - "348:150"
    - "361:25"
  91:
    - "51:1000"
    - "50:5"
    - "377:150"
    - "86:25"
  106:
    - "370:500"
    - "287:10"
    - "18:50"
    - "295:25"
  110:
    - "384:1000"
    - "39:3"
    - "372:25"
    - "40:3"
  111:
    - "106:5"
    - "349:150"
    - "361:25"
  115:
    - "369:250"
    - "372:5"
    - "370:250"
    - "40:25"
  127:
    - "354:1000"
    - "353:10"
    - "351:150"
  141:
    - "396:1000"
    - "391:5"
    - "398:150"
    - "141:100"
  142:
    - "142:100"
    - "392:5"
    - "394:50"
    - "393:25"

#############################################
#+-----------------------------------------+#
#|               Fish Drops                |#
#+-----------------------------------------+#
#############################################

# Enabled (boolean)
fishDropsEnabled: true

# Done based on level (up to 10)
# Items Dropped
# Format: 
#  [level]:
#    - "rewardId:chance out of 100"
fishDropItems:
  0:
    - "301:10"
    - "268:5"
  1:
    - "269:5"
    - "346:10"
  2:
    - "270:15"
    - "298:5"
  3:
    - "300:5"
    - "271:5"
  4:
    - "290:5"
    - "291:15"
  5:
    - "273:10"
    - "275:5"
  6:
    - "277:15"
    - "279:15"
  7:
    - "276:10"
    - "278:10"
  8:
    - "57:1"
    - "42:1"
    
#############################################
#+-----------------------------------------+#
#|           Block Redemption              |#
#+-----------------------------------------+#
#############################################
    
# Block Redemption Enabled (boolean)
redemptionEnabled: true

# Blacklisted Materials for Building Redeem
# Format: - material
redemptionBlacklist:
- diamond_block
- emerald_block
- iron_block
- gold_block
- diamond_ore
- emerald_ore
- iron_ore
- gold_ore
- obsidian
- beacon
- tnt
- pumpkin_stem
- melon_stem
- nether_warts
- potatoes
- potato_item
- carrots
- carrot_item
- crops
- fire